In [323]:
import numpy as np
import json
import csv
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
import seaborn as sns
import optuna
%matplotlib inline
np.set_printoptions(precision=3, suppress=True)

In [324]:
def load_data():
    data = pd.read_pickle('../../data/dataframes/data.pkl')
    nomination_onehot = pd.read_pickle('../../data/dataframes/nomination_onehot.pkl')
    selected_performers_onehot = pd.read_pickle('../../data/dataframes/selected_performers_onehot.pkl')
    selected_directors_onehot = pd.read_pickle('../../data/dataframes/selected_directors_onehot.pkl')
    selected_studio_onehot = pd.read_pickle('../../data/dataframes/selected_studio_onehot.pkl')
    selected_scriptwriter_onehot = pd.read_pickle('../../data/dataframes/selected_scriptwriter_onehot.pkl')
    review_dataframe = pd.read_pickle('../../data/dataframes/review_dataframe.pkl')
    
    # selected_directors_onehotとselected_scriptwriter_onehotの重複した人
    duplicate_scriptwriter = set(selected_directors_onehot.columns) & set(selected_scriptwriter_onehot.columns)
    selected_scriptwriter_onehot = selected_scriptwriter_onehot.drop(duplicate_scriptwriter, axis=1)
    
    frames = [nomination_onehot,selected_performers_onehot,selected_directors_onehot,selected_studio_onehot,selected_scriptwriter_onehot]
    
    df = data
    for f in frames:
        df = pd.merge(df, f, on='id')
    
    drop_elements = ["director", "other_nominates", "performers", "production_studio", "scriptwriter", "title",  'selected_performers', 'selected_directors', 'selected_studio',
       'selected_scriptwriter']
    df_drop = df.drop(drop_elements, axis=1)

    return df_drop, data

In [325]:
def standard(x_train, x_test):
    stdsc = StandardScaler()

    # 訓練用のデータを標準化
    x_train_std = stdsc.fit_transform(x_train)
    # 訓練用データを基準にテストデータも標準化
    x_test_std = stdsc.transform(x_test)
    
    return x_train_std, x_test_std

In [326]:
# 多重共線性の排除 (共分散0.7以上のfeatureを削除)

def collinearity(X):

    # 改善前
#     cor=np.corrcoef(X.T)
#     type(cor)
#     plt.figure(figsize=(20, 20))
#     sns.heatmap(cor, vmin=0.70,vmax=1,cmap=plt.cm.Spectral_r)

    # 改善
    drop_clm = ['吉田一夫']
    X = X.drop(drop_clm,  axis=1)

    # 改善後
    
#     cor=np.corrcoef(X.T)
#     type(cor)
#     plt.figure(figsize=(20, 20))
#     sns.heatmap(cor, vmin=0.80,vmax=1,cmap=plt.cm.Spectral_r)
    
    return X

In [327]:
def data_processing(test_year):
    df, data = load_data()
    
    df = collinearity(df)
    
    train = df.loc[df["year"] != test_year]
    test = df.loc[df["year"] == test_year]
    
    # 入力データの作成
    y_train = train['prize'].ravel()
    x_train = train.drop(['prize', 'year'], axis=1)
    
    features = x_train.columns
    
    x_train = x_train.values # 学習データ
    
    # テストデータの作成
    y_test = test['prize'].ravel()
    x_test = test.drop(['prize', 'year'], axis=1)
    x_test = x_test.values # テストデータ

    # データの標準化
    x_train_std, x_test_std = standard(x_train, x_test)
    
    return x_train_std, x_test_std, y_train, y_test, features

In [328]:
def plot_roc_curve(fpr, tpr, auc):
    # ROC曲線をプロット
    plt.plot(fpr, tpr, label='ROC curve (area = %.2f)'%auc)
    plt.legend()
    plt.title('ROC curve')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.grid(True)
    plt.show()

In [335]:
def lda(trial):
    
    th_prob = 0.5
    
    shrinkage = trial.suggest_uniform('shrinkage', 0, 1)
    
    print("shrinkage: ", shrinkage)
    cm_all = np.zeros((2, 2))
    
    # 予測した確率全体を格納
    probs_all = np.array([])
    y_true_all = np.array([])
    
    for y in range(1978, 2020):
        
        # データの生成
        x_train_std, x_test_std, y_train, y_test, features = data_processing(y)
        
        # 学習
        trained = LDA(solver="eigen", shrinkage=shrinkage).fit(x_train_std,  y_train)
        
        # 予測(確率)
        probs = trained.predict_proba(x_test_std)
        probs_all = np.hstack((probs_all, probs[:,1]))
        y_true_all = np.hstack((y_true_all, y_test))
#         print(probs)
#         print()
        
        # 混同行列
        y_pred = np.where((probs[:,1] ==  max(probs[:,1])) | (probs[:,1] > th_prob), 1, 0) #確率→0/1
        cm = confusion_matrix(y_true=y_test, y_pred=y_pred)
        cm_all += cm

    auc = roc_auc_score(y_true_all, probs_all)
    fpr, tpr, thresholds = roc_curve(y_true_all, probs_all)
    
#     plot_roc_curve(fpr, tpr, auc)
    
    print("len: {0} , {1}".format(len(y_true_all), len(probs_all) ))
    print("confusion_matrix: ")
    print(cm_all)
    print("AUC: ")
    print(auc)

    return -auc

In [336]:
def main():
    study = optuna.create_study()
    study.optimize(lda, n_trials=100)
    print(study.best_trial)

In [337]:
if __name__ == "__main__":
    main()

shrinkage:  0.05698468902981546
len: 211 , 211
confusion_matrix: 
[[139.  30.]
 [ 21.  21.]]
AUC: 
0.6748379825302903


[I 2019-08-21 05:54:33,804] Finished trial#0 resulted in value: -0.6748379825302903. Current best value is -0.6748379825302903 with parameters: {'shrinkage': 0.05698468902981546}.


shrinkage:  0.9800238647558587
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7447168216398985


[I 2019-08-21 05:54:42,283] Finished trial#1 resulted in value: -0.7447168216398985. Current best value is -0.7447168216398985 with parameters: {'shrinkage': 0.9800238647558587}.


shrinkage:  0.6936686144557905
len: 211 , 211
confusion_matrix: 
[[144.  25.]
 [ 20.  22.]]
AUC: 
0.7214708368554522


[I 2019-08-21 05:54:51,822] Finished trial#2 resulted in value: -0.7214708368554522. Current best value is -0.7447168216398985 with parameters: {'shrinkage': 0.9800238647558587}.


shrinkage:  0.2644787970344997
len: 211 , 211
confusion_matrix: 
[[141.  28.]
 [ 21.  21.]]
AUC: 
0.678923640462102


[I 2019-08-21 05:55:00,676] Finished trial#3 resulted in value: -0.678923640462102. Current best value is -0.7447168216398985 with parameters: {'shrinkage': 0.9800238647558587}.


shrinkage:  0.2209086826720683
len: 211 , 211
confusion_matrix: 
[[141.  28.]
 [ 22.  20.]]
AUC: 
0.6752606367990983


[I 2019-08-21 05:55:09,190] Finished trial#4 resulted in value: -0.6752606367990983. Current best value is -0.7447168216398985 with parameters: {'shrinkage': 0.9800238647558587}.


shrinkage:  0.9348731974304363
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7421808960270498


[I 2019-08-21 05:55:18,687] Finished trial#5 resulted in value: -0.7421808960270498. Current best value is -0.7447168216398985 with parameters: {'shrinkage': 0.9800238647558587}.


shrinkage:  0.7170265252709648
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7237249929557622


[I 2019-08-21 05:55:30,762] Finished trial#6 resulted in value: -0.7237249929557622. Current best value is -0.7447168216398985 with parameters: {'shrinkage': 0.9800238647558587}.


shrinkage:  0.30152212480963536
len: 211 , 211
confusion_matrix: 
[[141.  28.]
 [ 21.  21.]]
AUC: 
0.6816004508312201


[I 2019-08-21 05:55:39,860] Finished trial#7 resulted in value: -0.6816004508312201. Current best value is -0.7447168216398985 with parameters: {'shrinkage': 0.9800238647558587}.


shrinkage:  0.5555617274201786
len: 211 , 211
confusion_matrix: 
[[143.  26.]
 [ 20.  22.]]
AUC: 
0.7113271344040575


[I 2019-08-21 05:55:49,002] Finished trial#8 resulted in value: -0.7113271344040575. Current best value is -0.7447168216398985 with parameters: {'shrinkage': 0.9800238647558587}.


shrinkage:  0.7150850396590233
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 20.  22.]]
AUC: 
0.7235841081994928


[I 2019-08-21 05:55:58,132] Finished trial#9 resulted in value: -0.7235841081994928. Current best value is -0.7447168216398985 with parameters: {'shrinkage': 0.9800238647558587}.


shrinkage:  0.9909456786655961
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7451394759087067


[I 2019-08-21 05:56:07,373] Finished trial#10 resulted in value: -0.7451394759087067. Current best value is -0.7451394759087067 with parameters: {'shrinkage': 0.9909456786655961}.


shrinkage:  0.9880362195078457
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7444350521273598


[I 2019-08-21 05:56:16,975] Finished trial#11 resulted in value: -0.7444350521273598. Current best value is -0.7451394759087067 with parameters: {'shrinkage': 0.9909456786655961}.


shrinkage:  0.9019599613608634
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 21.  21.]]
AUC: 
0.7386587771203155


[I 2019-08-21 05:56:25,991] Finished trial#12 resulted in value: -0.7386587771203155. Current best value is -0.7451394759087067 with parameters: {'shrinkage': 0.9909456786655961}.


shrinkage:  0.9991351368453869
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.745280360664976


[I 2019-08-21 05:56:37,342] Finished trial#13 resulted in value: -0.745280360664976. Current best value is -0.745280360664976 with parameters: {'shrinkage': 0.9991351368453869}.


shrinkage:  0.8377008209740877
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7340095801634263


[I 2019-08-21 05:56:46,360] Finished trial#14 resulted in value: -0.7340095801634263. Current best value is -0.745280360664976 with parameters: {'shrinkage': 0.9991351368453869}.


shrinkage:  0.49089263894566615
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 21.  21.]]
AUC: 
0.7032967032967034


[I 2019-08-21 05:56:56,508] Finished trial#15 resulted in value: -0.7032967032967034. Current best value is -0.745280360664976 with parameters: {'shrinkage': 0.9991351368453869}.


shrinkage:  0.8408880435743992
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7341504649196957


[I 2019-08-21 05:57:08,040] Finished trial#16 resulted in value: -0.7341504649196957. Current best value is -0.745280360664976 with parameters: {'shrinkage': 0.9991351368453869}.


shrinkage:  0.5102532797914692
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 21.  21.]]
AUC: 
0.7062552831783602


[I 2019-08-21 05:57:17,512] Finished trial#17 resulted in value: -0.7062552831783602. Current best value is -0.745280360664976 with parameters: {'shrinkage': 0.9991351368453869}.


shrinkage:  0.8038507629001816
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7306283460129614


[I 2019-08-21 05:57:26,708] Finished trial#18 resulted in value: -0.7306283460129614. Current best value is -0.745280360664976 with parameters: {'shrinkage': 0.9991351368453869}.


shrinkage:  0.9910396802956415
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7451394759087067


[I 2019-08-21 05:57:36,039] Finished trial#19 resulted in value: -0.7451394759087067. Current best value is -0.745280360664976 with parameters: {'shrinkage': 0.9991351368453869}.


shrinkage:  0.6005243070069461
len: 211 , 211
confusion_matrix: 
[[143.  26.]
 [ 20.  22.]]
AUC: 
0.7144265990419837


[I 2019-08-21 05:57:45,182] Finished trial#20 resulted in value: -0.7144265990419837. Current best value is -0.745280360664976 with parameters: {'shrinkage': 0.9991351368453869}.


shrinkage:  0.9995487211347018
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.745280360664976


[I 2019-08-21 05:57:54,124] Finished trial#21 resulted in value: -0.745280360664976. Current best value is -0.745280360664976 with parameters: {'shrinkage': 0.9991351368453869}.


shrinkage:  0.9924818766214292
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7454212454212453


[I 2019-08-21 05:58:03,118] Finished trial#22 resulted in value: -0.7454212454212453. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.8983468888508629
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 21.  21.]]
AUC: 
0.7382361228515074


[I 2019-08-21 05:58:11,962] Finished trial#23 resulted in value: -0.7382361228515074. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.7880885258876666
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7296421527190757


[I 2019-08-21 05:58:20,809] Finished trial#24 resulted in value: -0.7296421527190757. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.39782945228763616
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 21.  21.]]
AUC: 
0.6935756551141167


[I 2019-08-21 05:58:29,570] Finished trial#25 resulted in value: -0.6935756551141167. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.8853603049655278
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 21.  21.]]
AUC: 
0.7368272752888136


[I 2019-08-21 05:58:38,862] Finished trial#26 resulted in value: -0.7368272752888136. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.04931053492084925
len: 211 , 211
confusion_matrix: 
[[139.  30.]
 [ 20.  22.]]
AUC: 
0.6738517892364047


[I 2019-08-21 05:58:49,881] Finished trial#27 resulted in value: -0.6738517892364047. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.6463825969228196
len: 211 , 211
confusion_matrix: 
[[143.  26.]
 [ 20.  22.]]
AUC: 
0.7182304874612566


[I 2019-08-21 05:58:59,725] Finished trial#28 resulted in value: -0.7182304874612566. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.15458943979647194
len: 211 , 211
confusion_matrix: 
[[141.  28.]
 [ 22.  20.]]
AUC: 
0.672442941673711


[I 2019-08-21 05:59:09,268] Finished trial#29 resulted in value: -0.672442941673711. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.7567302360372403
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7272471118624966


[I 2019-08-21 05:59:19,516] Finished trial#30 resulted in value: -0.7272471118624966. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.9899333802707723
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7451394759087068


[I 2019-08-21 05:59:28,396] Finished trial#31 resulted in value: -0.7451394759087068. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.9448558746449881
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7430262045646661


[I 2019-08-21 05:59:37,097] Finished trial#32 resulted in value: -0.7430262045646661. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.9616160221919754
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7438715131022824


[I 2019-08-21 05:59:46,417] Finished trial#33 resulted in value: -0.7438715131022824. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.999620647647325
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.745280360664976


[I 2019-08-21 05:59:55,361] Finished trial#34 resulted in value: -0.745280360664976. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.8637484198541483
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7357001972386588


[I 2019-08-21 06:00:05,806] Finished trial#35 resulted in value: -0.7357001972386588. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.9192063831358444
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7395040856579318


[I 2019-08-21 06:00:15,206] Finished trial#36 resulted in value: -0.7395040856579318. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.9906232238783256
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7449985911524374


[I 2019-08-21 06:00:24,720] Finished trial#37 resulted in value: -0.7449985911524374. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.8012117969638581
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7304874612566921


[I 2019-08-21 06:00:33,739] Finished trial#38 resulted in value: -0.7304874612566921. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.9363479469774375
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7426035502958579


[I 2019-08-21 06:00:42,839] Finished trial#39 resulted in value: -0.7426035502958579. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.8717173140905136
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7364046210200057


[I 2019-08-21 06:00:53,554] Finished trial#40 resulted in value: -0.7364046210200057. Current best value is -0.7454212454212453 with parameters: {'shrinkage': 0.9924818766214292}.


shrinkage:  0.9969036470087731
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7454212454212454


[I 2019-08-21 06:01:02,209] Finished trial#41 resulted in value: -0.7454212454212454. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9946732674189872
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7454212454212454


[I 2019-08-21 06:01:11,674] Finished trial#42 resulted in value: -0.7454212454212454. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9353399619202091
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7424626655395885


[I 2019-08-21 06:01:20,576] Finished trial#43 resulted in value: -0.7424626655395885. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9953991702264264
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7454212454212454


[I 2019-08-21 06:01:29,886] Finished trial#44 resulted in value: -0.7454212454212454. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9417782175273072
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7431670893209354


[I 2019-08-21 06:01:38,678] Finished trial#45 resulted in value: -0.7431670893209354. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.7369051367030008
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7249929557621866


[I 2019-08-21 06:01:47,961] Finished trial#46 resulted in value: -0.7249929557621866. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.6745626466680912
len: 211 , 211
confusion_matrix: 
[[143.  26.]
 [ 20.  22.]]
AUC: 
0.7197802197802198


[I 2019-08-21 06:01:56,784] Finished trial#47 resulted in value: -0.7197802197802198. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.8438228801810634
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7344322344322345


[I 2019-08-21 06:02:07,462] Finished trial#48 resulted in value: -0.7344322344322345. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9625457885972702
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7438715131022824


[I 2019-08-21 06:02:17,561] Finished trial#49 resulted in value: -0.7438715131022824. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.8991564168503461
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 21.  21.]]
AUC: 
0.7382361228515074


[I 2019-08-21 06:02:26,684] Finished trial#50 resulted in value: -0.7382361228515074. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9838449544133936
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7445759368836292


[I 2019-08-21 06:02:37,993] Finished trial#51 resulted in value: -0.7445759368836292. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9940646945961884
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7454212454212454


[I 2019-08-21 06:02:47,807] Finished trial#52 resulted in value: -0.7454212454212454. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9963210525451262
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.745280360664976


[I 2019-08-21 06:02:58,622] Finished trial#53 resulted in value: -0.745280360664976. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9135092966996455
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 21.  21.]]
AUC: 
0.739222316145393


[I 2019-08-21 06:03:08,500] Finished trial#54 resulted in value: -0.739222316145393. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.8275708466831024
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7333051563820794


[I 2019-08-21 06:03:19,047] Finished trial#55 resulted in value: -0.7333051563820794. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9654046063328803
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.744153282614821


[I 2019-08-21 06:03:29,039] Finished trial#56 resulted in value: -0.744153282614821. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.8744541980238925
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7359819667511975


[I 2019-08-21 06:03:38,659] Finished trial#57 resulted in value: -0.7359819667511975. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9987299843161995
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7454212454212454


[I 2019-08-21 06:03:47,781] Finished trial#58 resulted in value: -0.7454212454212454. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.7649461986546698
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7279515356438433


[I 2019-08-21 06:03:57,619] Finished trial#59 resulted in value: -0.7279515356438433. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.314837034238173
len: 211 , 211
confusion_matrix: 
[[141.  28.]
 [ 21.  21.]]
AUC: 
0.6837137221752607


[I 2019-08-21 06:04:08,324] Finished trial#60 resulted in value: -0.6837137221752607. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.955711590111976
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7434488588334742


[I 2019-08-21 06:04:21,983] Finished trial#61 resulted in value: -0.7434488588334742. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9999724382556077
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.745280360664976


[I 2019-08-21 06:04:31,771] Finished trial#62 resulted in value: -0.745280360664976. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9099419936763886
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 21.  21.]]
AUC: 
0.7389405466328542


[I 2019-08-21 06:04:42,726] Finished trial#63 resulted in value: -0.7389405466328542. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.012495226851766239
len: 211 , 211
confusion_matrix: 
[[139.  30.]
 [ 19.  23.]]
AUC: 
0.6770921386306002


[I 2019-08-21 06:04:52,433] Finished trial#64 resulted in value: -0.6770921386306002. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9997732652384589
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.745280360664976


[I 2019-08-21 06:05:02,318] Finished trial#65 resulted in value: -0.745280360664976. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9652046368697424
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.744153282614821


[I 2019-08-21 06:05:11,837] Finished trial#66 resulted in value: -0.744153282614821. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9233321757155287
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7400676246830094


[I 2019-08-21 06:05:21,222] Finished trial#67 resulted in value: -0.7400676246830094. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.8595579609766745
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7355593124823894


[I 2019-08-21 06:05:30,230] Finished trial#68 resulted in value: -0.7355593124823894. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.8193019188383528
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7326007326007327


[I 2019-08-21 06:05:39,611] Finished trial#69 resulted in value: -0.7326007326007327. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9681336763528591
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7441532826148209


[I 2019-08-21 06:05:48,770] Finished trial#70 resulted in value: -0.7441532826148209. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9939647106305526
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7454212454212454


[I 2019-08-21 06:05:57,797] Finished trial#71 resulted in value: -0.7454212454212454. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9992163137621443
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.745280360664976


[I 2019-08-21 06:06:06,908] Finished trial#72 resulted in value: -0.745280360664976. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9029987161547005
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 21.  21.]]
AUC: 
0.7387996618765849


[I 2019-08-21 06:06:16,058] Finished trial#73 resulted in value: -0.7387996618765849. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9406631993650062
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7430262045646661


[I 2019-08-21 06:06:25,503] Finished trial#74 resulted in value: -0.7430262045646661. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9726182656906223
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7442941673710903


[I 2019-08-21 06:06:34,819] Finished trial#75 resulted in value: -0.7442941673710903. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.8855087233777674
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 21.  21.]]
AUC: 
0.7368272752888136


[I 2019-08-21 06:06:44,288] Finished trial#76 resulted in value: -0.7368272752888136. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9996601977786571
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.745280360664976


[I 2019-08-21 06:06:54,027] Finished trial#77 resulted in value: -0.745280360664976. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9308693729532884
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7413355874894335


[I 2019-08-21 06:07:05,278] Finished trial#78 resulted in value: -0.7413355874894335. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9755349335335012
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.744153282614821


[I 2019-08-21 06:07:14,847] Finished trial#79 resulted in value: -0.744153282614821. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.4712929905726657
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 21.  21.]]
AUC: 
0.7017469709777402


[I 2019-08-21 06:07:24,129] Finished trial#80 resulted in value: -0.7017469709777402. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9992355573639972
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.745280360664976


[I 2019-08-21 06:07:33,554] Finished trial#81 resulted in value: -0.745280360664976. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9513221163811404
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7433079740772048


[I 2019-08-21 06:07:42,606] Finished trial#82 resulted in value: -0.7433079740772048. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9965635275655305
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7454212454212454


[I 2019-08-21 06:07:51,999] Finished trial#83 resulted in value: -0.7454212454212454. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9265058825057042
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7404902789518174


[I 2019-08-21 06:08:01,803] Finished trial#84 resulted in value: -0.7404902789518174. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.9772037955343035
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7447168216398985


[I 2019-08-21 06:08:11,056] Finished trial#85 resulted in value: -0.7447168216398985. Current best value is -0.7454212454212454 with parameters: {'shrinkage': 0.9969036470087731}.


shrinkage:  0.8867878611974853


KeyboardInterrupt: 

In [ ]:
# svd: 0.6786418709495633
#l sqr: 0.6786418709495633
# eigen: 0.6786418709495633


# eigen auto
# 0.745280360664976