In [1]:
import numpy as np
import json
import csv
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
import seaborn as sns
import optuna
%matplotlib inline
np.set_printoptions(precision=3, suppress=True)

In [2]:
def load_data(y):
    path = '../../data/std_data/'
    x_train_std = pd.read_pickle(path +'train/{}_x.pkl'.format(str(y))).values
    x_test_std = pd.read_pickle(path +'test/{}_x.pkl'.format(str(y))).values
    y_train = pd.read_pickle(path +'train/{}_y.pkl'.format(str(y))).values
    y_test = pd.read_pickle(path +'test/{}_y.pkl'.format(str(y))).values
    features = pd.read_pickle(path +'train/{}_x.pkl'.format(str(y))).columns
    return x_train_std, x_test_std, y_train, y_test, features

In [3]:
def plot_roc_curve(fpr, tpr, auc):
    # ROC曲線をプロット
    plt.plot(fpr, tpr, label='ROC curve (area = %.2f)'%auc)
    plt.legend()
    plt.title('ROC curve')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.grid(True)
    plt.show()

In [10]:
def lda(trial):
    
    th_prob = 0.5
    
    shrinkage = trial.suggest_uniform('shrinkage', 0, 1)
    
    print("shrinkage: ", shrinkage)
    cm_all = np.zeros((2, 2))
    
    # 予測した確率全体を格納
    probs_all = np.array([])
    y_true_all = np.array([])
    
    for y in range(1978, 2020):
        
        # データの生成
        x_train_std, x_test_std, y_train, y_test, features = load_data(y)
        
        # 学習
        trained = LDA(solver="eigen", shrinkage=shrinkage).fit(x_train_std,  y_train)
        
        # 予測(確率)
        probs = trained.predict_proba(x_test_std)
        probs_all = np.hstack((probs_all, probs[:,1]))
        y_true_all = np.hstack((y_true_all, y_test))
        
        # 混同行列
        y_pred = np.where((probs[:,1] ==  max(probs[:,1])) | (probs[:,1] > th_prob), 1, 0) #確率→0/1
        cm = confusion_matrix(y_true=y_test, y_pred=y_pred)
        cm_all += cm

    auc = roc_auc_score(y_true_all, probs_all)
    fpr, tpr, thresholds = roc_curve(y_true_all, probs_all)
    
#     plot_roc_curve(fpr, tpr, auc)
    
    print("len: {0} , {1}".format(len(y_true_all), len(probs_all) ))
    print("confusion_matrix: ")
    print(cm_all)
    print("AUC: ")
    print(auc)

    return -auc

In [11]:
def main():
    study = optuna.create_study()
    study.optimize(lda, n_trials=100)
    print(study.best_trial)

In [12]:
if __name__ == "__main__":
    main()

shrinkage:  0.4968883256324452
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 21.  21.]]
AUC: 
0.6979430825584673


[I 2019-08-23 01:31:27,884] Finished trial#0 resulted in value: -0.6979430825584673. Current best value is -0.6979430825584673 with parameters: {'shrinkage': 0.4968883256324452}.


shrinkage:  0.22462667462506603
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 21.  21.]]
AUC: 
0.666384897154128


[I 2019-08-23 01:31:28,406] Finished trial#1 resulted in value: -0.666384897154128. Current best value is -0.6979430825584673 with parameters: {'shrinkage': 0.4968883256324452}.


shrinkage:  0.19733108247907616
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 22.  20.]]
AUC: 
0.665257819103973


[I 2019-08-23 01:31:28,930] Finished trial#2 resulted in value: -0.665257819103973. Current best value is -0.6979430825584673 with parameters: {'shrinkage': 0.4968883256324452}.


shrinkage:  0.9162273825769557
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7362637362637363


[I 2019-08-23 01:31:29,499] Finished trial#3 resulted in value: -0.7362637362637363. Current best value is -0.7362637362637363 with parameters: {'shrinkage': 0.9162273825769557}.


shrinkage:  0.7107335219568304
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 20.  22.]]
AUC: 
0.7196393350239504


[I 2019-08-23 01:31:30,113] Finished trial#4 resulted in value: -0.7196393350239504. Current best value is -0.7362637362637363 with parameters: {'shrinkage': 0.9162273825769557}.


shrinkage:  0.9648740483179331
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7406311637080868


[I 2019-08-23 01:31:30,772] Finished trial#5 resulted in value: -0.7406311637080868. Current best value is -0.7406311637080868 with parameters: {'shrinkage': 0.9648740483179331}.


shrinkage:  0.40726485893882236
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 21.  21.]]
AUC: 
0.68836291913215


[I 2019-08-23 01:31:31,275] Finished trial#6 resulted in value: -0.68836291913215. Current best value is -0.7406311637080868 with parameters: {'shrinkage': 0.9648740483179331}.


shrinkage:  0.7734416573155524
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7251338405184559


[I 2019-08-23 01:31:32,049] Finished trial#7 resulted in value: -0.7251338405184559. Current best value is -0.7406311637080868 with parameters: {'shrinkage': 0.9648740483179331}.


shrinkage:  0.47694340795648515
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 21.  21.]]
AUC: 
0.6948436179205411


[I 2019-08-23 01:31:32,731] Finished trial#8 resulted in value: -0.6948436179205411. Current best value is -0.7406311637080868 with parameters: {'shrinkage': 0.9648740483179331}.


shrinkage:  0.9580995348891025
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7407720484643561


[I 2019-08-23 01:31:33,412] Finished trial#9 resulted in value: -0.7407720484643561. Current best value is -0.7407720484643561 with parameters: {'shrinkage': 0.9580995348891025}.


shrinkage:  0.7226337854134238
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7207664130741053


[I 2019-08-23 01:31:33,983] Finished trial#10 resulted in value: -0.7207664130741053. Current best value is -0.7407720484643561 with parameters: {'shrinkage': 0.9580995348891025}.


shrinkage:  0.9897436755011041
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7416173570019724


[I 2019-08-23 01:31:34,522] Finished trial#11 resulted in value: -0.7416173570019724. Current best value is -0.7416173570019724 with parameters: {'shrinkage': 0.9897436755011041}.


shrinkage:  0.9943268320223053
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7423217807833192


[I 2019-08-23 01:31:34,981] Finished trial#12 resulted in value: -0.7423217807833192. Current best value is -0.7423217807833192 with parameters: {'shrinkage': 0.9943268320223053}.


shrinkage:  0.8285922919369475
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7299239222316145


[I 2019-08-23 01:31:35,468] Finished trial#13 resulted in value: -0.7299239222316145. Current best value is -0.7423217807833192 with parameters: {'shrinkage': 0.9943268320223053}.


shrinkage:  0.6413111506991476
len: 211 , 211
confusion_matrix: 
[[143.  26.]
 [ 20.  22.]]
AUC: 
0.7131586362355593


[I 2019-08-23 01:31:35,961] Finished trial#14 resulted in value: -0.7131586362355593. Current best value is -0.7423217807833192 with parameters: {'shrinkage': 0.9943268320223053}.


shrinkage:  0.9882767134266338
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.741476472245703


[I 2019-08-23 01:31:36,417] Finished trial#15 resulted in value: -0.741476472245703. Current best value is -0.7423217807833192 with parameters: {'shrinkage': 0.9943268320223053}.


shrinkage:  0.8406078817849989
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7313327697943083


[I 2019-08-23 01:31:36,889] Finished trial#16 resulted in value: -0.7313327697943083. Current best value is -0.7423217807833192 with parameters: {'shrinkage': 0.9943268320223053}.


shrinkage:  0.08532445900309815
len: 211 , 211
confusion_matrix: 
[[138.  31.]
 [ 22.  20.]]
AUC: 
0.6549732318963087


[I 2019-08-23 01:31:37,389] Finished trial#17 resulted in value: -0.6549732318963087. Current best value is -0.7423217807833192 with parameters: {'shrinkage': 0.9943268320223053}.


shrinkage:  0.6149533852148243
len: 211 , 211
confusion_matrix: 
[[143.  26.]
 [ 20.  22.]]
AUC: 
0.7117497886728656


[I 2019-08-23 01:31:37,898] Finished trial#18 resulted in value: -0.7117497886728656. Current best value is -0.7423217807833192 with parameters: {'shrinkage': 0.9943268320223053}.


shrinkage:  0.8728674148573531
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7337278106508877


[I 2019-08-23 01:31:38,412] Finished trial#19 resulted in value: -0.7337278106508877. Current best value is -0.7423217807833192 with parameters: {'shrinkage': 0.9943268320223053}.


shrinkage:  0.9947082815731083
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7423217807833192


[I 2019-08-23 01:31:38,924] Finished trial#20 resulted in value: -0.7423217807833192. Current best value is -0.7423217807833192 with parameters: {'shrinkage': 0.9943268320223053}.


shrinkage:  0.9938100726164629
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7424626655395886


[I 2019-08-23 01:31:39,433] Finished trial#21 resulted in value: -0.7424626655395886. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9990907805945658
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7417582417582417


[I 2019-08-23 01:31:39,944] Finished trial#22 resulted in value: -0.7417582417582417. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8911669425248836
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7349957734573119


[I 2019-08-23 01:31:40,435] Finished trial#23 resulted in value: -0.7349957734573119. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.791504743779669
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7268244575936884


[I 2019-08-23 01:31:40,941] Finished trial#24 resulted in value: -0.7268244575936884. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9041128689447797
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.736122851507467


[I 2019-08-23 01:31:41,465] Finished trial#25 resulted in value: -0.736122851507467. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.6214688788983067
len: 211 , 211
confusion_matrix: 
[[143.  26.]
 [ 20.  22.]]
AUC: 
0.7120315581854043


[I 2019-08-23 01:31:42,009] Finished trial#26 resulted in value: -0.7120315581854043. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9982607563313063
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7417582417582417


[I 2019-08-23 01:31:42,503] Finished trial#27 resulted in value: -0.7417582417582417. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.7246690567689258
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.720625528317836


[I 2019-08-23 01:31:43,006] Finished trial#28 resulted in value: -0.720625528317836. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9239173960166486
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7369681600450831


[I 2019-08-23 01:31:43,475] Finished trial#29 resulted in value: -0.7369681600450831. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.37426970727695197
len: 211 , 211
confusion_matrix: 
[[141.  28.]
 [ 21.  21.]]
AUC: 
0.6832910679064526


[I 2019-08-23 01:31:43,956] Finished trial#30 resulted in value: -0.6832910679064526. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9954671434212472
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7423217807833192


[I 2019-08-23 01:31:44,460] Finished trial#31 resulted in value: -0.7423217807833192. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8468623512889979
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7318963088193857


[I 2019-08-23 01:31:44,985] Finished trial#32 resulted in value: -0.7318963088193857. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9932333425917688
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7423217807833192


[I 2019-08-23 01:31:45,534] Finished trial#33 resulted in value: -0.7423217807833192. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9288389151346741
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.73767258382643


[I 2019-08-23 01:31:46,038] Finished trial#34 resulted in value: -0.73767258382643. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.7864094386487568
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7259791490560721


[I 2019-08-23 01:31:46,536] Finished trial#35 resulted in value: -0.7259791490560721. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.938396762929578
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.738799661876585


[I 2019-08-23 01:31:47,166] Finished trial#36 resulted in value: -0.738799661876585. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.27290272039337005
len: 211 , 211
confusion_matrix: 
[[141.  28.]
 [ 21.  21.]]
AUC: 
0.671738517892364


[I 2019-08-23 01:31:47,674] Finished trial#37 resulted in value: -0.671738517892364. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8633511009546804
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7328825021132713


[I 2019-08-23 01:31:48,273] Finished trial#38 resulted in value: -0.7328825021132713. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9993509724025251
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7417582417582417


[I 2019-08-23 01:31:48,960] Finished trial#39 resulted in value: -0.7417582417582417. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9462353956159598
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7393632009016624


[I 2019-08-23 01:31:49,710] Finished trial#40 resulted in value: -0.7393632009016624. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.979914729089027
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7418991265145111


[I 2019-08-23 01:31:50,427] Finished trial#41 resulted in value: -0.7418991265145111. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9031783329767445
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7358410819949281


[I 2019-08-23 01:31:51,217] Finished trial#42 resulted in value: -0.7358410819949281. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9532366744688157
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 19.  23.]]
AUC: 
0.7400676246830094


[I 2019-08-23 01:31:51,834] Finished trial#43 resulted in value: -0.7400676246830094. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9963942493457529
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7420400112707805


[I 2019-08-23 01:31:52,553] Finished trial#44 resulted in value: -0.7420400112707805. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8144114170306809
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7296421527190758


[I 2019-08-23 01:31:53,161] Finished trial#45 resulted in value: -0.7296421527190758. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.5518082239857498
len: 211 , 211
confusion_matrix: 
[[143.  26.]
 [ 20.  22.]]
AUC: 
0.7045646661031276


[I 2019-08-23 01:31:53,745] Finished trial#46 resulted in value: -0.7045646661031276. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8965859080193844
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7357001972386589


[I 2019-08-23 01:31:54,305] Finished trial#47 resulted in value: -0.7357001972386589. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.7606275276276893
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.724429416737109


[I 2019-08-23 01:31:54,808] Finished trial#48 resulted in value: -0.724429416737109. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9578396759981156
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7406311637080867


[I 2019-08-23 01:31:55,305] Finished trial#49 resulted in value: -0.7406311637080867. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.03251803655824309
len: 211 , 211
confusion_matrix: 
[[137.  32.]
 [ 21.  21.]]
AUC: 
0.6511693434770357


[I 2019-08-23 01:31:55,816] Finished trial#50 resulted in value: -0.6511693434770357. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9829535143620652
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7416173570019723


[I 2019-08-23 01:31:56,318] Finished trial#51 resulted in value: -0.7416173570019723. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9935193866326651
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7424626655395886


[I 2019-08-23 01:31:56,823] Finished trial#52 resulted in value: -0.7424626655395886. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8731302697349302
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7335869258946183


[I 2019-08-23 01:31:57,336] Finished trial#53 resulted in value: -0.7335869258946183. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9532038922776004
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 19.  23.]]
AUC: 
0.7400676246830094


[I 2019-08-23 01:31:57,834] Finished trial#54 resulted in value: -0.7400676246830094. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8276971582362543
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7299239222316145


[I 2019-08-23 01:31:58,344] Finished trial#55 resulted in value: -0.7299239222316145. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9084722099381408
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7362637362637363


[I 2019-08-23 01:31:58,867] Finished trial#56 resulted in value: -0.7362637362637363. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9949103368327568
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7423217807833192


[I 2019-08-23 01:31:59,371] Finished trial#57 resulted in value: -0.7423217807833192. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8718797968481935
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7337278106508877


[I 2019-08-23 01:31:59,893] Finished trial#58 resulted in value: -0.7337278106508877. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9974998305098566
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7421808960270498


[I 2019-08-23 01:32:00,415] Finished trial#59 resulted in value: -0.7421808960270498. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9615972542846414
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7409129332206255


[I 2019-08-23 01:32:00,923] Finished trial#60 resulted in value: -0.7409129332206255. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.923145832401518
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7368272752888136


[I 2019-08-23 01:32:01,442] Finished trial#61 resulted in value: -0.7368272752888136. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9749430809099036
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.741476472245703


[I 2019-08-23 01:32:01,938] Finished trial#62 resulted in value: -0.741476472245703. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9962340436816526
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7420400112707805


[I 2019-08-23 01:32:02,444] Finished trial#63 resulted in value: -0.7420400112707805. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9291876984127313
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.73767258382643


[I 2019-08-23 01:32:02,936] Finished trial#64 resulted in value: -0.73767258382643. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8882338570133779
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7348548887010425


[I 2019-08-23 01:32:03,452] Finished trial#65 resulted in value: -0.7348548887010425. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9996183912907433
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7418991265145111


[I 2019-08-23 01:32:04,051] Finished trial#66 resulted in value: -0.7418991265145111. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9690135028163015
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7406311637080867


[I 2019-08-23 01:32:04,770] Finished trial#67 resulted in value: -0.7406311637080867. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.7535043424784994
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7230205691744153


[I 2019-08-23 01:32:05,521] Finished trial#68 resulted in value: -0.7230205691744153. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8109482745327041
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 20.  22.]]
AUC: 
0.7296421527190758


[I 2019-08-23 01:32:06,253] Finished trial#69 resulted in value: -0.7296421527190758. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8517012421126232
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7321780783319246


[I 2019-08-23 01:32:06,960] Finished trial#70 resulted in value: -0.7321780783319246. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9916903388928946
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7418991265145112


[I 2019-08-23 01:32:07,717] Finished trial#71 resulted in value: -0.7418991265145112. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.932918378947083
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7378134685826994


[I 2019-08-23 01:32:08,450] Finished trial#72 resulted in value: -0.7378134685826994. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9627184565453024
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7409129332206255


[I 2019-08-23 01:32:09,126] Finished trial#73 resulted in value: -0.7409129332206255. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9156161383008491
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7362637362637363


[I 2019-08-23 01:32:09,838] Finished trial#74 resulted in value: -0.7362637362637363. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9414754019303604
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7396449704142012


[I 2019-08-23 01:32:10,553] Finished trial#75 resulted in value: -0.7396449704142012. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9968156892679103
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7420400112707805


[I 2019-08-23 01:32:11,300] Finished trial#76 resulted in value: -0.7420400112707805. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.6632878849140356
len: 211 , 211
confusion_matrix: 
[[143.  26.]
 [ 20.  22.]]
AUC: 
0.714567483798253


[I 2019-08-23 01:32:12,066] Finished trial#77 resulted in value: -0.714567483798253. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8937694476236866
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7351366582135812


[I 2019-08-23 01:32:12,782] Finished trial#78 resulted in value: -0.7351366582135812. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.2743534365848488
len: 211 , 211
confusion_matrix: 
[[141.  28.]
 [ 21.  21.]]
AUC: 
0.6723020569174415


[I 2019-08-23 01:32:13,492] Finished trial#79 resulted in value: -0.6723020569174415. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9785329754159008
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7417582417582417


[I 2019-08-23 01:32:14,284] Finished trial#80 resulted in value: -0.7417582417582417. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9970110430631992
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7420400112707805


[I 2019-08-23 01:32:15,057] Finished trial#81 resulted in value: -0.7420400112707805. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9453905426416774
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7395040856579318


[I 2019-08-23 01:32:15,844] Finished trial#82 resulted in value: -0.7395040856579318. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9977698210245595
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7420400112707805


[I 2019-08-23 01:32:16,679] Finished trial#83 resulted in value: -0.7420400112707805. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9730925952188415
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7410538179768948


[I 2019-08-23 01:32:17,573] Finished trial#84 resulted in value: -0.7410538179768948. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9205563784112578
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7365455057762751


[I 2019-08-23 01:32:18,353] Finished trial#85 resulted in value: -0.7365455057762751. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9956214275296142
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7421808960270498


[I 2019-08-23 01:32:19,215] Finished trial#86 resulted in value: -0.7421808960270498. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9516630365120553
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7402085094392786


[I 2019-08-23 01:32:20,042] Finished trial#87 resulted in value: -0.7402085094392786. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.1727470855849359
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 22.  20.]]
AUC: 
0.6642716258100874


[I 2019-08-23 01:32:20,619] Finished trial#88 resulted in value: -0.6642716258100874. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8858974500363985
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7347140039447732


[I 2019-08-23 01:32:21,379] Finished trial#89 resulted in value: -0.7347140039447732. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9995759916250849
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7418991265145111


[I 2019-08-23 01:32:22,043] Finished trial#90 resulted in value: -0.7418991265145111. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.47366880221124397
len: 211 , 211
confusion_matrix: 
[[142.  27.]
 [ 21.  21.]]
AUC: 
0.6947027331642717


[I 2019-08-23 01:32:22,759] Finished trial#91 resulted in value: -0.6947027331642717. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9729967502568485
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7410538179768948


[I 2019-08-23 01:32:23,343] Finished trial#92 resulted in value: -0.7410538179768948. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9443975008464213
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 20.  22.]]
AUC: 
0.7397858551704706


[I 2019-08-23 01:32:23,883] Finished trial#93 resulted in value: -0.7397858551704706. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9788279714993383
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7417582417582417


[I 2019-08-23 01:32:24,396] Finished trial#94 resulted in value: -0.7417582417582417. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9998050226403327
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7418991265145111


[I 2019-08-23 01:32:24,898] Finished trial#95 resulted in value: -0.7418991265145111. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9111348812730353
len: 211 , 211
confusion_matrix: 
[[146.  23.]
 [ 21.  21.]]
AUC: 
0.7361228515074669


[I 2019-08-23 01:32:25,402] Finished trial#96 resulted in value: -0.7361228515074669. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.9602503142896206
len: 211 , 211
confusion_matrix: 
[[148.  21.]
 [ 18.  24.]]
AUC: 
0.7406311637080867


[I 2019-08-23 01:32:25,879] Finished trial#97 resulted in value: -0.7406311637080867. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.8538602187834515
len: 211 , 211
confusion_matrix: 
[[145.  24.]
 [ 21.  21.]]
AUC: 
0.7324598478444633


[I 2019-08-23 01:32:26,378] Finished trial#98 resulted in value: -0.7324598478444633. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


shrinkage:  0.93021352343778
len: 211 , 211
confusion_matrix: 
[[147.  22.]
 [ 21.  21.]]
AUC: 
0.7376725838264299


[I 2019-08-23 01:32:26,881] Finished trial#99 resulted in value: -0.7376725838264299. Current best value is -0.7424626655395886 with parameters: {'shrinkage': 0.9938100726164629}.


FrozenTrial(number=21, state=<TrialState.COMPLETE: 1>, value=-0.7424626655395886, datetime_start=datetime.datetime(2019, 8, 23, 1, 31, 38, 928883), datetime_complete=datetime.datetime(2019, 8, 23, 1, 31, 39, 431084), params={'shrinkage': 0.9938100726164629}, distributions={'shrinkage': UniformDistribution(low=0, high=1)}, user_attrs={}, system_attrs={'_number': 21}, intermediate_values={}, params_in_internal_repr={'shrinkage': 0.9938100726164629}, trial_id=21)


# 結果
shrinkage = 1 or "auto"