In [25]:
import numpy as np
import json
import csv
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
import optuna
%matplotlib inline

In [26]:
def load_data():
    data = pd.read_pickle('../../data/dataframes/data.pkl')
    nomination_onehot = pd.read_pickle('../../data/dataframes/nomination_onehot.pkl')
    selected_performers_onehot = pd.read_pickle('../../data/dataframes/selected_performers_onehot.pkl')
    selected_directors_onehot = pd.read_pickle('../../data/dataframes/selected_directors_onehot.pkl')
    selected_studio_onehot = pd.read_pickle('../../data/dataframes/selected_studio_onehot.pkl')
    selected_scriptwriter_onehot = pd.read_pickle('../../data/dataframes/selected_scriptwriter_onehot.pkl')
    review_dataframe = pd.read_pickle('../../data/dataframes/review_dataframe.pkl')

    frames = [nomination_onehot,selected_performers_onehot,selected_directors_onehot,selected_studio_onehot,selected_scriptwriter_onehot]

    df = data
    for f in frames:
        df = pd.merge(df, f, on='id')
    
    drop_elements = ["director", "other_nominates", "performers", "production_studio", "scriptwriter", "title",  'selected_performers', 'selected_directors', 'selected_studio',
       'selected_scriptwriter']
    df_drop = df.drop(drop_elements, axis=1)

    return df_drop, data

In [27]:
def standard(x_train, x_test):
    stdsc = StandardScaler()

    # 訓練用のデータを標準化
    x_train_std = stdsc.fit_transform(x_train)
    # 訓練用データを基準にテストデータも標準化
    x_test_std = stdsc.transform(x_test)
    
    return x_train_std, x_test_std

In [28]:
def data_processing(test_year):
    df, data = load_data()
    
    train = df.loc[df["year"] != test_year]
    test = df.loc[df["year"] == test_year]
    
    # 入力データの作成
    y_train = train['prize'].ravel()
    x_train = train.drop(['prize', 'year'], axis=1)
    
    features = x_train.columns
    
    x_train = x_train.values # 学習データ
    
    # テストデータの作成
    y_test = test['prize'].ravel()
    x_test = test.drop(['prize', 'year'], axis=1)
    x_test = x_test.values # テストデータ

    # データの標準化
    x_train_std, x_test_std = standard(x_train, x_test)
    
    return x_train_std, x_test_std, y_train, y_test, features

In [29]:
def print_weight_map(weight, features):
    # feature importance
    feature_imp = weight.reshape(features.shape)
    feature_imp_arg = np.argsort(feature_imp)
    f_num = len(feature_imp_arg)
    plt.rcParams["font.family"] = "IPAexGothic"
    plt.figure(figsize=(20,20))
    plt.barh(range(len(feature_imp_arg)), feature_imp[feature_imp_arg], color='b', align='center')
    plt.yticks(range(len(feature_imp_arg)), features[feature_imp_arg])
    plt.show()

In [30]:
def plot_roc_curve(fpr, tpr):
    # ROC曲線をプロット
    plt.plot(fpr, tpr, label='ROC curve (area = %.2f)'%auc)
    plt.legend()
    plt.title('ROC curve')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.grid(True)
    plt.show()

In [31]:
# optunaで最適なC_valを探す

def train(trial):
    
    th_prob = 0.5
    C_val = trial.suggest_uniform('C_val', 0.000001, 0.001)
    
    print(" C_val:{}".format(C_val))
    
    cm_all = np.zeros((2, 2))
    
    # 予測した確率全体を格納
    probs_all = np.array([])
    y_true_all = np.array([])
    
    for y in range(1978, 2020):
        
        # データの生成
        x_train_std, x_test_std, y_train, y_test, features = data_processing(y)
        
        # 学習
        lr = LogisticRegression(class_weight="balanced", solver="liblinear",  penalty='l2', C=C_val) # ロジスティック回帰モデルのインスタンスを作成
        lr.fit(x_train_std, y_train) # ロジスティック回帰モデルの重みを学習
        
        # 予測(確率)
        probs = lr.predict_proba(x_test_std)
        probs_all = np.hstack((probs_all, probs[:,1]))
        y_true_all = np.hstack((y_true_all, y_test))
#         print(probs)
#         print()
        
        # 混同行列
        y_pred = np.where((probs[:,1] ==  max(probs[:,1])) | (probs[:,1] > th_prob), 1, 0) #確率→0/1
        cm = confusion_matrix(y_true=y_test, y_pred=y_pred)
        cm_all += cm
        
       # 各特徴量の重み係数
        weight = lr.coef_
        
        
#         print_weight_map(weight, features)

    auc = roc_auc_score(y_true_all, probs_all)
    fpr, tpr, thresholds = roc_curve(y_true_all, probs_all)
    
#     plot_roc_curve(fpr, tpr)
    
    print("len: {0} , {1}".format(len(y_true_all), len(probs_all) ))
    print("confusion_matrix: ")
    print(cm_all)
    print("AUC: ")
    print(auc)
#     print()
    return -auc

In [32]:
def main():
    np.set_printoptions(precision=3, suppress=True)
    study = optuna.create_study()
    study.optimize(train, n_trials=100)
    print(study.best_trial)

In [34]:
# l2
if __name__ == "__main__":
    main()

 C_val:9.963958532085081e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:38:08,869] Finished trial#0 resulted in value: -0.7558467173851788. Current best value is -0.7558467173851788 with parameters: {'C_val': 9.963958532085081e-05}.


 C_val:0.000409930628192413
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 13.  29.]]
AUC: 
0.7534516765285996


[I 2019-08-21 01:38:16,772] Finished trial#1 resulted in value: -0.7534516765285996. Current best value is -0.7558467173851788 with parameters: {'C_val': 9.963958532085081e-05}.


 C_val:0.00048213174096335345
len: 211 , 211
confusion_matrix: 
[[117.  52.]
 [ 13.  29.]]
AUC: 
0.7530290222597914


[I 2019-08-21 01:38:25,346] Finished trial#2 resulted in value: -0.7530290222597914. Current best value is -0.7558467173851788 with parameters: {'C_val': 9.963958532085081e-05}.


 C_val:0.00018597774760543064
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 12.  30.]]
AUC: 
0.7552831783601014


[I 2019-08-21 01:38:34,476] Finished trial#3 resulted in value: -0.7552831783601014. Current best value is -0.7558467173851788 with parameters: {'C_val': 9.963958532085081e-05}.


 C_val:0.00045381527964360655
len: 211 , 211
confusion_matrix: 
[[117.  52.]
 [ 13.  29.]]
AUC: 
0.7531699070160608


[I 2019-08-21 01:38:42,932] Finished trial#4 resulted in value: -0.7531699070160608. Current best value is -0.7558467173851788 with parameters: {'C_val': 9.963958532085081e-05}.


 C_val:4.801938052502636e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7561284868977176


[I 2019-08-21 01:38:51,758] Finished trial#5 resulted in value: -0.7561284868977176. Current best value is -0.7561284868977176 with parameters: {'C_val': 4.801938052502636e-05}.


 C_val:0.000688968451304336
len: 211 , 211
confusion_matrix: 
[[117.  52.]
 [ 13.  29.]]
AUC: 
0.752888137503522


[I 2019-08-21 01:39:00,194] Finished trial#6 resulted in value: -0.752888137503522. Current best value is -0.7561284868977176 with parameters: {'C_val': 4.801938052502636e-05}.


 C_val:0.0007812283049908938
len: 211 , 211
confusion_matrix: 
[[117.  52.]
 [ 13.  29.]]
AUC: 
0.7527472527472527


[I 2019-08-21 01:39:08,985] Finished trial#7 resulted in value: -0.7527472527472527. Current best value is -0.7561284868977176 with parameters: {'C_val': 4.801938052502636e-05}.


 C_val:5.514056903487039e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7559876021414482


[I 2019-08-21 01:39:17,131] Finished trial#8 resulted in value: -0.7559876021414482. Current best value is -0.7561284868977176 with parameters: {'C_val': 4.801938052502636e-05}.


 C_val:9.774738454687726e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7557058326289094


[I 2019-08-21 01:39:25,176] Finished trial#9 resulted in value: -0.7557058326289094. Current best value is -0.7561284868977176 with parameters: {'C_val': 4.801938052502636e-05}.


 C_val:0.0002986250421630853
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 13.  29.]]
AUC: 
0.7544378698224852


[I 2019-08-21 01:39:33,529] Finished trial#10 resulted in value: -0.7544378698224852. Current best value is -0.7561284868977176 with parameters: {'C_val': 4.801938052502636e-05}.


 C_val:1.879060470318369e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.756692025922795


[I 2019-08-21 01:39:43,538] Finished trial#11 resulted in value: -0.756692025922795. Current best value is -0.756692025922795 with parameters: {'C_val': 1.879060470318369e-05}.


 C_val:1.4217591031061077e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.756692025922795


[I 2019-08-21 01:39:53,315] Finished trial#12 resulted in value: -0.756692025922795. Current best value is -0.756692025922795 with parameters: {'C_val': 1.879060470318369e-05}.


 C_val:0.00023027137583790788
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 12.  30.]]
AUC: 
0.755142293603832


[I 2019-08-21 01:40:02,150] Finished trial#13 resulted in value: -0.755142293603832. Current best value is -0.756692025922795 with parameters: {'C_val': 1.879060470318369e-05}.


 C_val:0.0006376440199378227
len: 211 , 211
confusion_matrix: 
[[117.  52.]
 [ 13.  29.]]
AUC: 
0.7530290222597914


[I 2019-08-21 01:40:10,676] Finished trial#14 resulted in value: -0.7530290222597914. Current best value is -0.756692025922795 with parameters: {'C_val': 1.879060470318369e-05}.


 C_val:0.000990609107739226
len: 211 , 211
confusion_matrix: 
[[116.  53.]
 [ 13.  29.]]
AUC: 
0.751338405184559


[I 2019-08-21 01:40:18,897] Finished trial#15 resulted in value: -0.751338405184559. Current best value is -0.756692025922795 with parameters: {'C_val': 1.879060470318369e-05}.


 C_val:2.7031205295232697e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:40:27,430] Finished trial#16 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.0003168752839726178
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 13.  29.]]
AUC: 
0.7542969850662158


[I 2019-08-21 01:40:38,545] Finished trial#17 resulted in value: -0.7542969850662158. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.0001717503021654207
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7554240631163708


[I 2019-08-21 01:40:47,518] Finished trial#18 resulted in value: -0.7554240631163708. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00087978183631394
len: 211 , 211
confusion_matrix: 
[[117.  52.]
 [ 13.  29.]]
AUC: 
0.7514792899408284


[I 2019-08-21 01:40:55,550] Finished trial#19 resulted in value: -0.7514792899408284. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:4.646196718856559e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:41:04,940] Finished trial#20 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:1.0756382105023105e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:41:13,729] Finished trial#21 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00014668402124242024
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7554240631163708


[I 2019-08-21 01:41:22,954] Finished trial#22 resulted in value: -0.7554240631163708. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00027691062681571945
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 13.  29.]]
AUC: 
0.7545787545787545


[I 2019-08-21 01:41:31,403] Finished trial#23 resulted in value: -0.7545787545787545. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:2.6091215164609774e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7564102564102563


[I 2019-08-21 01:41:39,804] Finished trial#24 resulted in value: -0.7564102564102563. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00012609744036016097
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7554240631163708


[I 2019-08-21 01:41:48,253] Finished trial#25 resulted in value: -0.7554240631163708. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:6.155995008842389e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:41:56,372] Finished trial#26 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00021726365517935007
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 12.  30.]]
AUC: 
0.755142293603832


[I 2019-08-21 01:42:04,573] Finished trial#27 resulted in value: -0.755142293603832. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00037339933303392044
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 13.  29.]]
AUC: 
0.7538743307974077


[I 2019-08-21 01:42:12,725] Finished trial#28 resulted in value: -0.7538743307974077. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.0001043658530702231
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:42:21,428] Finished trial#29 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.0005673556932066682
len: 211 , 211
confusion_matrix: 
[[117.  52.]
 [ 13.  29.]]
AUC: 
0.7531699070160608


[I 2019-08-21 01:42:30,023] Finished trial#30 resulted in value: -0.7531699070160608. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:3.4827642898444447e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:42:38,625] Finished trial#31 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:8.728206757324693e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:42:47,026] Finished trial#32 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:4.419372801572513e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:42:55,699] Finished trial#33 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:7.29871230132659e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:43:04,283] Finished trial#34 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.0001812191577818158
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 12.  30.]]
AUC: 
0.7554240631163708


[I 2019-08-21 01:43:12,936] Finished trial#35 resulted in value: -0.7554240631163708. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:7.878921553577813e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:43:21,225] Finished trial#36 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00023832474248698633
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 12.  30.]]
AUC: 
0.755142293603832


[I 2019-08-21 01:43:29,794] Finished trial#37 resulted in value: -0.755142293603832. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00013965985944138927
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7554240631163708


[I 2019-08-21 01:43:38,036] Finished trial#38 resulted in value: -0.7554240631163708. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:6.807214747497187e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:43:49,040] Finished trial#39 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00040861798045013705
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 13.  29.]]
AUC: 
0.753592561284869


[I 2019-08-21 01:43:58,013] Finished trial#40 resulted in value: -0.753592561284869. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:5.466499670348404e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:44:07,411] Finished trial#41 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:5.56846173045061e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7559876021414482


[I 2019-08-21 01:44:16,290] Finished trial#42 resulted in value: -0.7559876021414482. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00011349342036466149
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:44:25,458] Finished trial#43 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:2.1592511997595073e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:44:35,142] Finished trial#44 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:5.179848212675171e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7561284868977176


[I 2019-08-21 01:44:43,312] Finished trial#45 resulted in value: -0.7561284868977176. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.0001597318742969836
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7552831783601014


[I 2019-08-21 01:44:52,145] Finished trial#46 resulted in value: -0.7552831783601014. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:4.3120510488640635e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:45:00,973] Finished trial#47 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:9.22359860429546e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7557058326289094


[I 2019-08-21 01:45:09,530] Finished trial#48 resulted in value: -0.7557058326289094. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:4.4254433038748245e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7561284868977176


[I 2019-08-21 01:45:18,380] Finished trial#49 resulted in value: -0.7561284868977176. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00020512759800212697
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 12.  30.]]
AUC: 
0.755142293603832


[I 2019-08-21 01:45:26,907] Finished trial#50 resulted in value: -0.755142293603832. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:3.536695526818103e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:45:35,698] Finished trial#51 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:3.994722913078707e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.756269371653987


[I 2019-08-21 01:45:43,795] Finished trial#52 resulted in value: -0.756269371653987. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:7.0899087284463575e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:45:52,085] Finished trial#53 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00011459883678261702
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:46:00,401] Finished trial#54 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:7.584144980426921e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:46:09,532] Finished trial#55 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:3.6954404108767e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.756269371653987


[I 2019-08-21 01:46:18,365] Finished trial#56 resulted in value: -0.756269371653987. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.0007659315441198443
len: 211 , 211
confusion_matrix: 
[[117.  52.]
 [ 13.  29.]]
AUC: 
0.7527472527472527


[I 2019-08-21 01:46:26,851] Finished trial#57 resulted in value: -0.7527472527472527. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00014857219975212727
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7554240631163708


[I 2019-08-21 01:46:35,453] Finished trial#58 resulted in value: -0.7554240631163708. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.000993768948951066
len: 211 , 211
confusion_matrix: 
[[116.  53.]
 [ 13.  29.]]
AUC: 
0.751338405184559


[I 2019-08-21 01:46:44,004] Finished trial#59 resulted in value: -0.751338405184559. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:1.420857329618384e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:46:53,294] Finished trial#60 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:2.814386729610338e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7564102564102563


[I 2019-08-21 01:47:02,244] Finished trial#61 resulted in value: -0.7564102564102563. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:8.091316069155044e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7559876021414482


[I 2019-08-21 01:47:11,002] Finished trial#62 resulted in value: -0.7559876021414482. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:3.755967660097304e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:47:19,310] Finished trial#63 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:8.863433328821532e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:47:28,472] Finished trial#64 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00010567576926003532
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:47:36,925] Finished trial#65 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.0005479301207877038
len: 211 , 211
confusion_matrix: 
[[117.  52.]
 [ 13.  29.]]
AUC: 
0.7531699070160608


[I 2019-08-21 01:47:45,036] Finished trial#66 resulted in value: -0.7531699070160608. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00026435976985748276
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 13.  29.]]
AUC: 
0.7548605240912932


[I 2019-08-21 01:47:53,077] Finished trial#67 resulted in value: -0.7548605240912932. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:4.502111946930309e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7561284868977176


[I 2019-08-21 01:48:01,368] Finished trial#68 resulted in value: -0.7561284868977176. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.0001902877108702411
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 12.  30.]]
AUC: 
0.7554240631163708


[I 2019-08-21 01:48:10,237] Finished trial#69 resulted in value: -0.7554240631163708. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00012467401139292634
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7554240631163708


[I 2019-08-21 01:48:19,075] Finished trial#70 resulted in value: -0.7554240631163708. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:6.108375333216457e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:48:28,094] Finished trial#71 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:6.910309707056694e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:48:37,431] Finished trial#72 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:2.4187954898298336e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7564102564102563


[I 2019-08-21 01:48:50,589] Finished trial#73 resulted in value: -0.7564102564102563. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:3.196120566066683e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7564102564102563


[I 2019-08-21 01:48:59,160] Finished trial#74 resulted in value: -0.7564102564102563. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:7.11072614254901e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:49:07,476] Finished trial#75 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.000949770232154676
len: 211 , 211
confusion_matrix: 
[[116.  53.]
 [ 13.  29.]]
AUC: 
0.7516201746970977


[I 2019-08-21 01:49:16,236] Finished trial#76 resulted in value: -0.7516201746970977. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:5.602698913940988e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:49:24,448] Finished trial#77 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.0003370014406740216
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 13.  29.]]
AUC: 
0.7540152155536771


[I 2019-08-21 01:49:32,673] Finished trial#78 resulted in value: -0.7540152155536771. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:1.6612763130503828e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:49:40,663] Finished trial#79 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00010252942488010992
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:49:48,772] Finished trial#80 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:2.641865504882705e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:49:57,073] Finished trial#81 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:5.279195186726749e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7561284868977176


[I 2019-08-21 01:50:06,270] Finished trial#82 resulted in value: -0.7561284868977176. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:3.442578582226443e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7564102564102563


[I 2019-08-21 01:50:15,441] Finished trial#83 resulted in value: -0.7564102564102563. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:8.618918100087753e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7559876021414482


[I 2019-08-21 01:50:23,653] Finished trial#84 resulted in value: -0.7559876021414482. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:5.357340508218782e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7561284868977176


[I 2019-08-21 01:50:31,796] Finished trial#85 resulted in value: -0.7561284868977176. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:1.76758799023306e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.756692025922795


[I 2019-08-21 01:50:40,098] Finished trial#86 resulted in value: -0.756692025922795. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00013219018598971744
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7554240631163708


[I 2019-08-21 01:50:51,336] Finished trial#87 resulted in value: -0.7554240631163708. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:2.0474485469496127e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.756692025922795


[I 2019-08-21 01:51:01,602] Finished trial#88 resulted in value: -0.756692025922795. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00015683820469668264
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7552831783601014


[I 2019-08-21 01:51:10,621] Finished trial#89 resulted in value: -0.7552831783601014. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:6.29506129885273e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7558467173851788


[I 2019-08-21 01:51:20,072] Finished trial#90 resulted in value: -0.7558467173851788. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:2.5946871776686985e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:51:29,384] Finished trial#91 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:3.222247188113994e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7564102564102563


[I 2019-08-21 01:51:39,591] Finished trial#92 resulted in value: -0.7564102564102563. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:9.289310606620795e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7557058326289094


[I 2019-08-21 01:51:48,146] Finished trial#93 resulted in value: -0.7557058326289094. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:3.6251919736918565e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:51:56,952] Finished trial#94 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:0.00047108424921062363
len: 211 , 211
confusion_matrix: 
[[117.  52.]
 [ 13.  29.]]
AUC: 
0.7530290222597914


[I 2019-08-21 01:52:05,626] Finished trial#95 resulted in value: -0.7530290222597914. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:5.897089936259354e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7559876021414482


[I 2019-08-21 01:52:14,590] Finished trial#96 resulted in value: -0.7559876021414482. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:2.3190974176656247e-05
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7565511411665257


[I 2019-08-21 01:52:22,794] Finished trial#97 resulted in value: -0.7565511411665257. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:1.647600045989233e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:52:30,890] Finished trial#98 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


 C_val:1.6827092494418026e-06
len: 211 , 211
confusion_matrix: 
[[118.  51.]
 [ 11.  31.]]
AUC: 
0.7568329106790644


[I 2019-08-21 01:52:41,001] Finished trial#99 resulted in value: -0.7568329106790644. Current best value is -0.7568329106790644 with parameters: {'C_val': 2.7031205295232697e-06}.


FrozenTrial(number=16, state=<TrialState.COMPLETE: 1>, value=-0.7568329106790644, datetime_start=datetime.datetime(2019, 8, 21, 1, 40, 18, 900144), datetime_complete=datetime.datetime(2019, 8, 21, 1, 40, 27, 428912), params={'C_val': 2.7031205295232697e-06}, distributions={'C_val': UniformDistribution(low=1e-06, high=0.001)}, user_attrs={}, system_attrs={'_number': 16}, intermediate_values={}, params_in_internal_repr={'C_val': 2.7031205295232697e-06}, trial_id=16)


In [ ]:
#  best value is -0.7550014088475626 with parameters: {'C_val': 0.00025433628983389037}.